# Place any default configuration for solr_wrapper here
# version: 6.0.0
# port: 8983
version: 7.7.2
download_dir: /var/tmp
instance_dir: tmp/solr-development
collection:
  persist: true
  dir: solr/conf/
  name: hydra-development
